SELECT IDHABITACION, round(AVG(NUMEROPERSONAS/CAPACIDAD), 3) as indice
FROM ESTADIAS,HABITACIONES,TIPOSHABITACION
WHERE ESTADIAS.IDHABITACION = HABITACIONES.NUMEROHABITACION
AND HABITACIONES.TIPOHABITACION = TIPOSHABITACION.IDTIPOHABITACION
GROUP BY IDHABITACION;
