INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (1,3);
--Fila 2
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (2,3);
--Fila 3
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (3,1);
--Fila 4
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (4,3);
--Fila 5
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (5,3);
--Fila 6
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (6,1);
--Fila 7
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (7,3);
--Fila 8
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (8,2);
--Fila 9
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (9,3);
--Fila 10
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (10,1);
--Fila 11
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (11,3);
--Fila 12
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (12,1);
--Fila 13
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (13,2);
--Fila 14
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (14,2);
--Fila 15
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (15,2);
--Fila 16
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (16,1);
--Fila 17
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (17,1);
--Fila 18
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (18,3);
--Fila 19
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (19,1);
--Fila 20
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (20,3);
--Fila 21
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (21,1);
--Fila 22
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (22,2);
--Fila 23
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (23,2);
--Fila 24
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (24,3);
--Fila 25
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (25,3);
--Fila 26
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (26,3);
--Fila 27
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (27,3);
--Fila 28
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (28,3);
--Fila 29
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (29,2);
--Fila 30
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (30,1);
--Fila 31
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (31,1);
--Fila 32
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (32,2);
--Fila 33
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (33,1);
--Fila 34
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (34,2);
--Fila 35
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (35,1);
--Fila 36
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (36,3);
--Fila 37
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (37,2);
--Fila 38
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (38,3);
--Fila 39
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (39,2);
--Fila 40
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (40,1);
--Fila 41
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (41,1);
--Fila 42
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (42,3);
--Fila 43
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (43,3);
--Fila 44
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (44,3);
--Fila 45
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (45,1);
--Fila 46
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (46,3);
--Fila 47
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (47,1);
--Fila 48
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (48,1);
--Fila 49
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (49,1);
--Fila 50
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (50,2);
--Fila 51
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (51,2);
--Fila 52
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (52,3);
--Fila 53
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (53,3);
--Fila 54
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (54,1);
--Fila 55
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (55,2);
--Fila 56
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (56,3);
--Fila 57
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (57,1);
--Fila 58
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (58,2);
--Fila 59
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (59,2);
--Fila 60
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (60,1);
--Fila 61
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (61,3);
--Fila 62
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (62,1);
--Fila 63
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (63,3);
--Fila 64
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (64,1);
--Fila 65
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (65,3);
--Fila 66
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (66,3);
--Fila 67
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (67,2);
--Fila 68
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (68,1);
--Fila 69
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (69,3);
--Fila 70
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (70,2);
--Fila 71
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (71,3);
--Fila 72
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (72,2);
--Fila 73
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (73,1);
--Fila 74
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (74,3);
--Fila 75
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (75,2);
--Fila 76
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (76,2);
--Fila 77
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (77,1);
--Fila 78
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (78,1);
--Fila 79
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (79,2);
--Fila 80
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (80,3);
--Fila 81
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (81,1);
--Fila 82
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (82,3);
--Fila 83
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (83,3);
--Fila 84
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (84,2);
--Fila 85
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (85,3);
--Fila 86
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (86,1);
--Fila 87
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (87,3);
--Fila 88
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (88,2);
--Fila 89
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (89,2);
--Fila 90
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (90,1);
--Fila 91
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (91,1);
--Fila 92
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (92,2);
--Fila 93
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (93,3);
--Fila 94
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (94,2);
--Fila 95
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (95,3);
--Fila 96
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (96,3);
--Fila 97
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (97,2);
--Fila 98
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (98,1);
--Fila 99
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (99,3);
--Fila 100
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (100,1);
--Fila 101
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (101,3);
--Fila 102
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (102,2);
--Fila 103
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (103,1);
--Fila 104
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (104,1);
--Fila 105
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (105,2);
--Fila 106
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (106,1);
--Fila 107
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (107,1);
--Fila 108
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (108,1);
--Fila 109
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (109,2);
--Fila 110
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (110,3);
--Fila 111
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (111,1);
--Fila 112
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (112,1);
--Fila 113
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (113,3);
--Fila 114
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (114,3);
--Fila 115
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (115,2);
--Fila 116
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (116,2);
--Fila 117
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (117,3);
--Fila 118
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (118,2);
--Fila 119
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (119,3);
--Fila 120
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (120,1);
--Fila 121
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (121,3);
--Fila 122
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (122,1);
--Fila 123
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (123,1);
--Fila 124
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (124,1);
--Fila 125
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (125,1);
--Fila 126
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (126,1);
--Fila 127
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (127,2);
--Fila 128
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (128,1);
--Fila 129
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (129,2);
--Fila 130
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (130,2);
--Fila 131
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (131,2);
--Fila 132
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (132,2);
--Fila 133
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (133,3);
--Fila 134
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (134,3);
--Fila 135
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (135,3);
--Fila 136
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (136,1);
--Fila 137
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (137,2);
--Fila 138
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (138,2);
--Fila 139
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (139,2);
--Fila 140
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (140,3);
--Fila 141
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (141,2);
--Fila 142
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (142,2);
--Fila 143
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (143,1);
--Fila 144
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (144,1);
--Fila 145
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (145,3);
--Fila 146
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (146,2);
--Fila 147
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (147,1);
--Fila 148
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (148,2);
--Fila 149
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (149,2);
--Fila 150
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (150,3);
--Fila 151
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (151,1);
--Fila 152
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (152,2);
--Fila 153
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (153,3);
--Fila 154
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (154,3);
--Fila 155
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (155,1);
--Fila 156
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (156,1);
--Fila 157
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (157,2);
--Fila 158
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (158,3);
--Fila 159
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (159,3);
--Fila 160
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (160,1);
--Fila 161
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (161,3);
--Fila 162
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (162,2);
--Fila 163
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (163,3);
--Fila 164
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (164,3);
--Fila 165
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (165,2);
--Fila 166
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (166,3);
--Fila 167
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (167,3);
--Fila 168
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (168,1);
--Fila 169
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (169,3);
--Fila 170
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (170,3);
--Fila 171
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (171,3);
--Fila 172
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (172,2);
--Fila 173
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (173,2);
--Fila 174
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (174,3);
--Fila 175
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (175,3);
--Fila 176
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (176,3);
--Fila 177
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (177,1);
--Fila 178
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (178,3);
--Fila 179
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (179,3);
--Fila 180
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (180,2);
--Fila 181
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (181,1);
--Fila 182
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (182,3);
--Fila 183
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (183,1);
--Fila 184
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (184,1);
--Fila 185
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (185,2);
--Fila 186
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (186,3);
--Fila 187
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (187,2);
--Fila 188
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (188,1);
--Fila 189
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (189,3);
--Fila 190
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (190,1);
--Fila 191
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (191,1);
--Fila 192
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (192,2);
--Fila 193
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (193,3);
--Fila 194
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (194,3);
--Fila 195
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (195,1);
--Fila 196
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (196,2);
--Fila 197
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (197,2);
--Fila 198
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (198,2);
--Fila 199
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (199,1);
--Fila 200
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (200,1);
--Fila 201
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (201,3);
--Fila 202
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (202,3);
--Fila 203
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (203,3);
--Fila 204
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (204,1);
--Fila 205
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (205,3);
--Fila 206
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (206,2);
--Fila 207
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (207,1);
--Fila 208
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (208,3);
--Fila 209
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (209,1);
--Fila 210
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (210,1);
--Fila 211
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (211,3);
--Fila 212
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (212,1);
--Fila 213
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (213,3);
--Fila 214
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (214,3);
--Fila 215
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (215,3);
--Fila 216
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (216,1);
--Fila 217
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (217,3);
--Fila 218
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (218,2);
--Fila 219
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (219,2);
--Fila 220
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (220,2);
--Fila 221
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (221,3);
--Fila 222
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (222,2);
--Fila 223
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (223,1);
--Fila 224
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (224,3);
--Fila 225
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (225,1);
--Fila 226
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (226,1);
--Fila 227
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (227,2);
--Fila 228
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (228,2);
--Fila 229
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (229,2);
--Fila 230
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (230,2);
--Fila 231
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (231,2);
--Fila 232
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (232,2);
--Fila 233
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (233,3);
--Fila 234
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (234,1);
--Fila 235
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (235,3);
--Fila 236
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (236,3);
--Fila 237
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (237,3);
--Fila 238
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (238,3);
--Fila 239
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (239,1);
--Fila 240
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (240,2);
--Fila 241
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (241,2);
--Fila 242
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (242,3);
--Fila 243
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (243,3);
--Fila 244
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (244,3);
--Fila 245
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (245,2);
--Fila 246
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (246,3);
--Fila 247
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (247,3);
--Fila 248
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (248,2);
--Fila 249
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (249,3);
--Fila 250
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (250,1);
--Fila 251
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (251,2);
--Fila 252
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (252,2);
--Fila 253
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (253,1);
--Fila 254
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (254,1);
--Fila 255
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (255,2);
--Fila 256
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (256,1);
--Fila 257
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (257,3);
--Fila 258
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (258,1);
--Fila 259
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (259,2);
--Fila 260
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (260,3);
--Fila 261
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (261,2);
--Fila 262
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (262,3);
--Fila 263
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (263,2);
--Fila 264
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (264,2);
--Fila 265
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (265,2);
--Fila 266
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (266,1);
--Fila 267
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (267,1);
--Fila 268
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (268,1);
--Fila 269
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (269,2);
--Fila 270
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (270,3);
--Fila 271
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (271,1);
--Fila 272
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (272,3);
--Fila 273
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (273,1);
--Fila 274
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (274,2);
--Fila 275
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (275,2);
--Fila 276
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (276,3);
--Fila 277
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (277,3);
--Fila 278
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (278,3);
--Fila 279
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (279,1);
--Fila 280
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (280,1);
--Fila 281
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (281,2);
--Fila 282
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (282,1);
--Fila 283
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (283,2);
--Fila 284
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (284,2);
--Fila 285
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (285,1);
--Fila 286
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (286,3);
--Fila 287
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (287,2);
--Fila 288
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (288,1);
--Fila 289
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (289,2);
--Fila 290
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (290,3);
--Fila 291
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (291,1);
--Fila 292
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (292,1);
--Fila 293
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (293,3);
--Fila 294
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (294,2);
--Fila 295
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (295,3);
--Fila 296
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (296,3);
--Fila 297
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (297,1);
--Fila 298
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (298,2);
--Fila 299
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (299,2);
--Fila 300
INSERT INTO HABITACIONES (NUMEROHABITACION, TIPOHABITACION) VALUES (300,2);
